### ISSUE TITLE
croak - Timer not active

### ISSUE THREAD

**Issue by karel-m** [kraih/mojo#1235]
* Mojolicious version: 7.84
* Perl version: 5.20.1
* Operating system: Linux / CentOS 6 / x86_64

```
CORE
  Perl        (v5.20.1, linux)
  Mojolicious (7.84, Doughnut)

OPTIONAL
  EV 4.0+                 (4.22)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 2.009+  (2.056)
  Net::DNS::Native 0.15+  (0.18)
  Role::Tiny 2.000001+    (2.000006)
```

### Actual behavior

After upgrading to Mojolicious 7.84 it happens that after some time our application starts to generate 
many errors: `Timer not active at /usr/local/perl520/site/lib/Mojo/Reactor/EV.pm line 12.`

Once it begins the errors are emitted approx. 6 per minute (not in even time periods) and the application starts to become unstable and needs to be restarted.

In our application we do quite often call `app->ua` to make a request to backend servers. Basically nearly every request from the outside causes at least one backed request via `Mojo::UserAgent` / `app->ua`.

I am mentioning this because according to my debugging the trouble seems to be somehow related to `Mojo::UserAgent`.  Here is a stack trace fragment:

```
Timer not active at /usr/local/perl520/site/lib/Mojo/Reactor/EV.pm line 12.
  Mojo::Reactor::EV::again(Mojo::Reactor::EV=HASH(0x52cf440), "46d1aa85a45276833763dccdbef3e7b0") called at /usr/local/perl520/site/lib/Mojo/IOLoop/Stream.pm line 93
  Mojo::IOLoop::Stream::_again(Mojo::IOLoop::Stream::HTTPClient=HASH(0xe063ac0)) called at /usr/local/perl520/site/lib/Mojo/IOLoop/Stream.pm line 27
  Mojo::IOLoop::Stream::is_readable(Mojo::IOLoop::Stream::HTTPClient=HASH(0xe063ac0)) called at /usr/local/perl520/site/lib/Mojo/UserAgent.pm line 240
  Mojo::UserAgent::_dequeue(Mojo::UserAgent=HASH(0xd393138), Mojo::IOLoop=HASH(0x4e52958), "http:127.0.0.1:54322", 1) called at /usr/local/perl520/site/lib/Mojo/UserAgent.pm line 207
  Mojo::UserAgent::_connection(Mojo::UserAgent=HASH(0xd393138), Mojo::IOLoop=HASH(0x4e52958), Mojo::Transaction::HTTP=HASH(0xe05e698), CODE(0xe06ee58)) called at /usr/local/perl520/site/lib/Mojo/UserAgent.pm line 311
  Mojo::UserAgent::_start(Mojo::UserAgent=HASH(0xd393138), Mojo::IOLoop=HASH(0x4e52958), Mojo::Transaction::HTTP=HASH(0xe05e698), CODE(0xe06ee58)) called at /usr/local/perl520/site/lib/Mojo/UserAgent.pm line 61
  Mojo::UserAgent::start(Mojo::UserAgent=HASH(0xd393138), Mojo::Transaction::HTTP=HASH(0xe05e698), CODE(0xe06ee58)) called at /opt/app/Portal/lib/Mojolicious/Plugin/AsqProxy/Ctrl.pm line 136
  (the next one is in our code)
```

### Expected behavior

Before the upgrade the same applications code run without any error like this (or similar).

### Steps to reproduce the behavior

This is the hardest part. 

I observe this trouble in our application approximately 4-times a week. The interesting fact is that we are running 2 production + 2 testing instances of the same application and just one of them (the one with the highest load) is throwing these errors. So it looks like a corner case which happens only under some pretty rare conditions (unfortunately not rare enough).

One thing that may be related is the following warning:
```
Mojo::IOLoop::Stream::HTTPClient:25:Can't call method "isa" on an undefined value
```

that usually (but not always) appears (onces) before the application starts with `Timer not active` errors.

The line in question: https://metacpan.org/source/SRI/Mojolicious-7.84/lib/Mojo/IOLoop/Stream/HTTPClient.pm#L25 The code obviously is not ready for a situation where `$self->handle` is undef. But my knowledge of Mojolicious internals is very limited therefore I have no idea whether it is related to our troubles with `Timer not active`.

**Comment by kraih** [comment]
I'm afraid there isn't much we can do without a way to replicate the behavior.

**Comment by kraih** [comment]
Afraid i have no idea what information would help. What's happening is pretty clear from the stack trace. Somehow the timer got lost in the reactor (maybe the stream timed out?), and then the stream still ended up in the `Mojo::UserAgent` connection pool. And things die when it checks if the connection is tainted. There is likely a very simple fix, but without a test case i wouldn't know where to start.

Unfortunately we will have to wait until someone can provide us a script that replicates the problem. Or you manage to track it down on your production system before that happens.

**Comment by kraih** [comment]
If you set `$app->us->max_connections(0)` the problem will likely disappear (and there will be a significant performance loss).

**Comment by kraih** [comment]
The first question that needs to be answered is how the timer for removed from the reactor.

**Comment by kraih** [comment]
I do have a hunch that this patch might resolve the problem. But of course i can't test it.
```
diff --git a/lib/Mojo/IOLoop/Stream.pm b/lib/Mojo/IOLoop/Stream.pm
index 50fb52dbe..b681fc62e 100644
--- a/lib/Mojo/IOLoop/Stream.pm
+++ b/lib/Mojo/IOLoop/Stream.pm
@@ -70,8 +70,8 @@ sub timeout {
   $reactor->remove(delete $self->{timer}) if $self->{timer};
   return $self unless my $timeout = $self->{timeout} = shift;
   weaken $self;
-  $self->{timer}
-    = $reactor->timer($timeout => sub { $self->emit('timeout')->close });
+  $self->{timer} = $reactor->timer(
+    $timeout => sub { delete $self->{timer}; $self->emit('timeout')->close });

   return $self;
 }
```

**Comment by karel-m** [comment]
I have applied the above mentioned patch to `Mojo/IOLoop/Stream.pm` on our "trouble making" site. I'll post here how it went.

**Comment by kraih** [comment]
Any updates?

**Comment by karel-m** [comment]
No failures "Timer not active" since yesterday morning.

**Comment by karel-m** [comment]
Still no failures "Timer not active". 

Ad "unpatching & checking for CLOSE_WAIT" - I can do that but after the weekend.

Ad "details about blocking or non blocking I/O" - 100% non-bloking, no exceptions.

**Comment by karel-m** [comment]
Meanwhile another our site (not the patched one) start croaking "Timer not active" (after 2-3 weeks running without troubles) - so I have checked for CLOSE_WAIT sockets, there were none.

**Comment by kraih** [comment]
I've released Mojolicious 7.88 with the change.

**Comment by karel-m** [comment]
I have upgraded our production sites to 7.88.

Thank you - not only for helping with this issue but also for creating and maintaining such a mighty piece of software.

**Comment by karel-m** [comment]
Meanwhile:
 * I have created a similar issue #1247
 * the change https://github.com/kraih/mojo/issues/1235#issuecomment-403315750 was reverted by bdc185c
 * the fix for #1247 2865f3b was released as 7.90
 * after all that I still see `Timer not active` on our trouble making site

**Comment by kraih** [comment]
That's unfortunate, but we are not going to try anything until there is a test case we can use to replicate the problem. Like there was for #1247.

**Comment by karel-m** [comment]
I am not sure if it is important, but this is how we set up UserAgent's timeouts:
```
$app->ua->max_connections(100)->inactivity_timeout(60)->request_timeout(0)->connect_timeout(10);
```

**Comment by karel-m** [comment]
I have noticed fca6eb342f09 

Thank you.

**Comment by karel-m** [comment]
Closing; however I have a new one (I'll create a new issue)
